version: "3"
services:
  pgsql:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  calendar:
    image: calendar:develop
    ports:
      - "127.0.0.1:4200:4200"
      - "127.0.0.1:4300:4300"
    env_file:
      - .env
    depends_on: [ pgsql, rabbitmq ]

  scheduler:
    image: scheduler:develop
    env_file:
      - .env
    depends_on: [ pgsql, rabbitmq ]

  sender:
    image: sender:develop
    env_file:
      - .env
    depends_on: [ rabbitmq ]

